### ISSUE TITLE
fragment appears in every page or not shown while printing pdf file

### ISSUE THREAD

**Issue by libralibra** [Martinomagnifico/reveal.js-appearance#13]
The fragment with `li class="fragment"` will appear as steps on different pages without problem. If I add extra appearance class using `li class="fragment animate__skidLeft"`, then the list item will appear on every page. For instance, if the original slide has 3 fragments, then those with `animate__skidLeft` will appear on all 3 pages in the generated PDF, while the expected behaviour is that they should appear one after another on the 3 pages.

But the fragment appears perfectly fine in slide mode. The problem only affect the print-pdf functionality.

**Comment by Martinomagnifico** [comment]
Hi Daniel, good find. I’ll look into it.

**Comment by Martinomagnifico** [comment]
This is fixed in the latest version (1.3.4).

**Comment by libralibra** [comment]
> This is fixed in the latest version (1.3.4).

Just had a quick test and the bug was fixed! Great job!
