### ISSUE TITLE
Does not work within iframe

### ISSUE THREAD

**Issue by sp71** [Martinomagnifico/reveal.js-appearance#2]
I'm putting my reveal presentation within an iframe. All the plugins work for me except for this. Maybe because some event is not being captured because of the iframe? It works fine when there is no iframe. Any suggestions?

**Comment by sp71** [comment]
Found the issue. Within appearance init, I saw the following lines
```
window.addEventListener("slidechangecomplete", showHideSlide, false);
```

I fixed it by doing the following:

```
window.parent.addEventListener("slidechangecomplete", showHideSlide, false);
```

**Comment by sp71** [comment]
Would be good to also consider iframe for other users of this repo

**Comment by Martinomagnifico** [comment]
Thanks for the heads up! I'll look into the issue later this week.

**Comment by Martinomagnifico** [comment]
Hi Satinder, the issue was not in Appearance, but in Transit.js, which tracks if a Reveal transition has really ended. I've changed it there, so you should be good to go now. Thanks!
