### ISSUE TITLE
Fails when reveal.js 'fade' transition mode is enabled

### ISSUE THREAD

**Issue by kingofpayne** [Martinomagnifico/reveal.js-appearance#3]
The plugin fails to show and animate the elements when the reveal.js transition mode is set to 'fade' during initialization. Other transition modes are ok.

**Comment by kingofpayne** [comment]
The issue seems to come from transit.js which does not detect slide transition propertly when transition mode is 'fade'.
See https://github.com/Martinomagnifico/reveal.js-transit/pull/1 which seems to fix the issue.

**Comment by Martinomagnifico** [comment]
Merged it, thanks!
