### ISSUE TITLE
Animated elements in fragments

### ISSUE THREAD

**Issue by Zimbelstern** [Martinomagnifico/reveal.js-appearance#7]
Hi,
is there a setting to start the Appearance animation for a fragment not before the same fragment gets visible? At the moment, I have the problem, that the animation is already over when I tell reveal.js to show the fragment.

**Comment by Martinomagnifico** [comment]
I’ll take a look at it. Do you have an example?

**Comment by Zimbelstern** [comment]
Sure:
```
<div class="reveal">
	<div class="slides">
		<section>
			<p class="animate__bounceIn">First paragraph.</p>
			<p class="fragment animate__bounceIn">Second paragraph.</p>
		</section>
	</div>
</div>
```
The first paragraph bounces, the second one only if you are quick enough. ;-)

Here is the documentation for the fragments, in case you missed it:
[https://revealjs.com/fragments/](https://revealjs.com/fragments/)

**Comment by Martinomagnifico** [comment]
I’ll probably be able to look at it next weekend. In the meantime you might split the classes so that the fragment is an element wrapping the p. That is how I usually do it, because both the fragment and the animate.css classes use transitions on the opacity. Having that at the same time gives unpredictable results.

**Comment by Zimbelstern** [comment]
Great, many thanks, that seems to work. Wouldn't this be applicable to all cases?

**Comment by Martinomagnifico** [comment]
Yes it would. In the demo I refer to the use of Appearance inside fragments. Having a set of such items where the parent (the fragment) is the first of them, does also not make sense in order. However, I do not document that well enough. That will be done in the next release, which also has improvements for use inside MarkDown.

**Comment by Martinomagnifico** [comment]
Fragments can indeed have animations, but those work with transitions of certain properties, while Appearance uses ‘animation’. Mixing those is just unpredictable. I can 1) look into suppressing the transitions other than opacity for those situations, 2) improve docs and describe to not mix it, or 3) some combo of both in case people don’t read the docs.
